-- Add rdo_category_code to conceptos_servicio
ALTER TABLE public.conceptos_servicio
ADD COLUMN IF NOT EXISTS rdo_category_code text REFERENCES public.rdo_categories(code);

-- Add visible_local flag to hide brand-only services from local invoice selector
ALTER TABLE public.conceptos_servicio
ADD COLUMN IF NOT EXISTS visible_local boolean NOT NULL DEFAULT true;

-- Mark Canon Marca and Marketing Marca as not visible to locals (auto-generated by trigger)
UPDATE public.conceptos_servicio 
SET visible_local = false 
WHERE tipo = 'canon_marca';

-- Seed rdo_category_code for existing services based on their subcategoria
UPDATE public.conceptos_servicio SET rdo_category_code = 'alquiler' WHERE subcategoria = 'alquiler';
UPDATE public.conceptos_servicio SET rdo_category_code = 'expensas' WHERE subcategoria = 'gastos_comunes';
UPDATE public.conceptos_servicio SET rdo_category_code = 'fee_marca' WHERE subcategoria = 'fee_marca';
UPDATE public.conceptos_servicio SET rdo_category_code = 'marketing' WHERE subcategoria = 'marketing';
UPDATE public.conceptos_servicio SET rdo_category_code = 'bromatologia' WHERE subcategoria = 'bromatologia';
UPDATE public.conceptos_servicio SET rdo_category_code = 'estudio_contable' WHERE subcategoria = 'contador';
UPDATE public.conceptos_servicio SET rdo_category_code = 'software_gestion' WHERE subcategoria = 'software';
UPDATE public.conceptos_servicio SET rdo_category_code = 'energia_electrica' WHERE subcategoria = 'energia_electrica';
UPDATE public.conceptos_servicio SET rdo_category_code = 'gas' WHERE subcategoria = 'gas_natural';
UPDATE public.conceptos_servicio SET rdo_category_code = 'internet_telefonia' WHERE subcategoria = 'internet';